### ISSUE TITLE
The "Select a recall to view more details" instruction text is always present

### ISSUE THREAD

**Issue by belyea** [BridgePhase/ctf#39]
When first clicking on the 'Food' menu option, the clickable country is shown but with no recalls yet listed. However, on the right hand side, there is instructional text stating to select a recall. Is it possible to make this text only available when recall data is displayed? See screenshot.

![select recall instructions when no recalls present](https://cloud.githubusercontent.com/assets/11012844/8298074/d85b1d5a-1931-11e5-9485-5a9e1b3f627c.JPG)

**Comment by jgarciarbridgephase** [comment]
@belyea - 
So I'm moving this to Sprint 4 because I'm not really sure what to do about it right now. Taking the text off the screen looks quite blank. This is what it looks like right now

![screen shot 2015-06-24 at 7 50 03 pm](https://cloud.githubusercontent.com/assets/12414982/8344072/41d9d00e-1aaa-11e5-9b24-10a5d5b4fa0b.png)

FYI:
I implemented a "Test" environment so that we can test issues before we move to production. So can you please test this on http://54.175.58.210:8080/ctf/

Thanks!

**Comment by jgarciarbridgephase** [comment]
Added to #58, closing this one
